export enum AuthMessage {
  LoginError = 'Error loading categories',
  LoginFail = 'Login failed: Invalid email or password',
  LoginSuccess = 'Đăng nhập thành công',
  RegisterSuccess = 'Đăng ký thành công, vui lòng kiểm tra email kích hoạt tài khoản',
  RegisterFail = 'Đăng ký không thành công. Vui lòng thử lại',
  ExistUser = 'Tài khoản đã tồn tại',
  VerifyEmailFail = 'Token Không đúng',
  EmailNotActivated = 'Tài khoản chưa kích hoạt. Vui lòng kiểm tra email',
  VerifyEmailSuccess = 'Hướng dẫn để đặt lại mật khẩu đã gửi tới email của bạn',
  ForgotPasswordFail = 'Lấy lại mật khẩu không thành công. Vui lòng thử lại',
  ChangePasswordSuccess = 'Thay đổi mật khẩu thành công. Vui lòng quay lại trang đăng nhập',
  ChangePasswordFail = 'Thay đổi mật khẩu không thành công. Vui lòng thử lại',
  Verify = 'Đang kích hoạt tài khoản',
  VerifySuccess = 'Kích hoạt thành công',
}
